spring:
  datasource:
    url: jdbc:h2:mem:productDB
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6379

  application:
    name: spring-boot3-redis


logging:
  level:
    org:
      springframework:
        cache: DEBUG